---
sudo: false
before_script:
  - git clone https://github.com/exercism/problem-specifications.git
  - bin/fetch-configlet
  - docker build -t exercism-rakudo-star .
  - docker run
    --volume $PWD:/exercism
    exercism-rakudo-star perl6 -e
    '.add(‘Example.pm6’).copy(.dir.first({.extension eq ‘pm6’ && .basename ne ‘Example.pm6’}))
    for $*CWD.add(‘exercism/exercises’).dir' # replace stub files with complete solutions from Example.pm6
script:
  - bin/configlet lint .
  - docker run
    --volume $PWD:/exercism
    exercism-rakudo-star prove /exercism
    --exec perl6
    --recurse
    --jobs 2
