---
sudo: false
language: perl6
install:
  - rakudobrew build-panda
  - panda install JSON::Tiny
before_script:
  - bin/fetch-configlet
script:
  - bin/configlet .
  - EXERCISM=1 prove -vr --exec=perl6 exercises/
